name: proxy-manager

services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
    volumes:
      - /home/services/nginx/data:/data
      - /home/services/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    external: true